#!/usr/bin/env bash

WWW_ROOT="`pwd`"

ENV_FILE="${WWW_ROOT}/.env"

cp -f "${WWW_ROOT}/config.development.json.tpl" "${WWW_ROOT}/config.development.json";

# printf "\nPATH: ${WWW_ROOT}\n\n";

# detect OS
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     SED_CMD=sed;;
    Darwin*)    SED_CMD=gsed;;
    CYGWIN*)    SED_CMD=sed;;
    MINGW*)     SED_CMD=sed;;
    *)          SED_CMD=sed;;
esac

${SED_CMD} -e "s#%WWW_ROOT%#${WWW_ROOT}#g" -i "$WWW_ROOT/config.development.json";

old_IFS=$IFS;
IFS='
';
filelines=`cat $ENV_FILE`
for line in $filelines ; do
    KEY=$(echo ${line} | cut -d= -f1)
    VALUE=$(printf "%s" ${line} | cut -d= -f2 | tr -d "\r\n")
    # IFS="=" read ${KEY} VALUE <<< "${line}"
    ${SED_CMD} -i "s|%${KEY}%|${VALUE}|g" "$WWW_ROOT/config.development.json";
done;
IFS=${old_IFS};

# printf "${WWW_ROOT}/config.development.json\n\n"
# cat "${WWW_ROOT}/config.development.json";

# logs
mkdir -p ${WWW_ROOT}/content/logs

NODE_ENV="development" \
DEBUG=ghost:*,knex:*,ghost-config \
npx nodemon node_modules/ghost/index.js
