#!/usr/bin/env bash

WWW_ROOT="`pwd`"

cp -f "${WWW_ROOT}/config.development.json.tpl" "${WWW_ROOT}/config.development.json";

printf "\nPATH: ${WWW_ROOT}\n\n";

# detect OS
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     SED_CMD=sed;;
    Darwin*)    SED_CMD=gsed;;
    CYGWIN*)    SED_CMD=sed;;
    MINGW*)     SED_CMD=sed;;
    *)          SED_CMD=sed;;
esac

printf "OS: ${machine}";

${SED_CMD} -e "s|#WWW_ROOT#|${WWW_ROOT}|g" -i "$WWW_ROOT/config.development.json";

printf "${WWW_ROOT}/config.development.json\n\n"
cat "${WWW_ROOT}/config.development.json";

# logs
mkdir -p ${WWW_ROOT}/content/logs

NODE_ENV="development" DEBUG=ghost:*,knex:*,ghost-config node node_modules/ghost/index.js
